#!/bin/bash
# print information for i3blocks

print() {
	if ! [ -z $1 ]
	then
		echo $1
	else
		exit 1
	fi
}

full_text=$1
short_text=$2
color=$3
background=$4

print $full_text
print $short_text
print $color
print $background
